language: python
addons:
  postgresql: 9.3
python:
  - 2.6
  - 2.7
install:
  - pip install -e .[tests]
before_script:
  - psql -c "create user sqlalchemy_pilo with login password 'sqlalchemy_pilo';" -U postgres
  - psql -c "create database sqlalchemy_pilo with owner sqlalchemy_pilo;" -U postgres
script:
  - nosetests
